---
- hosts: build
  become: yes
  tasks:
    - name: install dependencies
      apt:
        pkg:
          - openjdk-8-jdk
          - maven
        update-cache: yes
        state: latest

    - name: import key
      get_url:
        url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
        dest: '/usr/share/keyrings/jenkins-keyring.asc'

    - name: Add jenkins repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: install jenkins package
      apt:
        name: jenkins 
        state: present
        
    - name: add jenkins to docker group
      user: 
        name: jenkins
        groups: docker
        append: yes

    - name: grant users access to docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0666'

  handlers:
  - name: start jenkins
    service: 
      name: jenkins 
      state: started