#launchInstances
- hosts: localhost
  vars:
    key_name: awsMaster
    ec2_instances:
      - name: ansible
        image: "ami-0279c3b3186e54acd"
        tags: 
          group: cfgMgmt
          Name: ansible
        # ssh_user: ubuntu

      - name: jenkins
        image: ami-0279c3b3186e54acd # Ubuntu 12.04
        tags: 
          group: build
          Name: jenkinsController
        # ssh_user: ubuntu

      - name: tomcat
        image: ami-0279c3b3186e54acd # Ubuntu 12.04
        tags: 
          group: compute
          Name: docker1
        # ssh_user: ubuntu

      - name: docker
        image: ami-0279c3b3186e54acd # Ubuntu 12.04
        tags: 
          group: compute
          Name: docker2
        # ssh_user: ubuntu

  tasks:
    - name: Create security group
      ec2_group:
        name: bms_sec_group
        description: ex sec group 1
        # vpc_id: 12345
        region: us-east-1
        # aws_access_key: "{{ my_access_key }}"
        # aws_secret_key: "{{ my_secret_key }}"
        # aws_security_token: "{{ my_security_token }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 8080
            cidr_ip: 50.52.25.142/32
            rule_desc: allow ssh and web svcs
          - proto: tcp
            ports:
              - 22
              - 50000
              - 2376
              - 4243
              - 32768-60999
            group_name: 
              - bms_sec_group
            rule_desc: allow internal API ports docker and jenkins

      register: result_sec_group
      
    - name: Launch Instance
      ec2:
        key_name: "{{key_name}}"
        group_id: "{{ result_sec_group.group_id }}"
        count: 1
        instance_type: t2.micro
        image: '{{ item.image }}'
        wait: yes
        region: 'us-east-1'
        instance_tags: "{{ item.tags }}"
      register: ec2
      with_items: "{{ ec2_instances }}"

    - debug:
        msg: "{{ item.name }}"
      with_items: "{{ ec2_instances }}"
