- name: setup SSH keys for AWS project
  hosts: localhost
 
  vars:
     key_name: awsMaster
     ansible_python_interpreter: /usr/bin/python3

  tasks:
   - name: create keypair in AWS instance
     ec2_key:
        # aws_access_key: "{{ my_access_key }}"
        # aws_secret_key: "{{ my_secret_key }}"
        # aws_security_token: "{{ my_security_token }}"
        name: "{{ key_name }}"
        key_material: "{{ item }}"
        region: us-east-1
     with_file: ./awsMaster.pub
     register: ec2_key_result
        # - debug:
        #      var: ec2_key.name
  #  - name: Create keys dir if not exist
  #    file:
  #       path: keys
  #       owner: jenkins
  #       group: jenkins
  #       mode: 0700
  #       state: directory
  #  - name: Store private key
  #    copy: content="{{ ec2_key_result.key.private_key }}" dest="./{{ key_name }}.pem" mode=0400
  #    when: ec2_key_result